version: '3.8'

services:
  supermarket-api:
    build: .
    container_name: supermarket-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:supermarketdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8080
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - supermarket-network

networks:
  supermarket-network:
    driver: bridge